
const products = [
        {
            "id":1,
            "name":"Chair",
            "price":100,
            "image":"images/shpCart/armChair.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":2,
            "name":"Camera",
            "price":200,
            "image":"images/shpCart/camera.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":3,
            "name":"Clock",
            "price":50,
            "image":"images/shpCart/clock.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":4,
            "name":"headphone",
            "price":250,
            "image":"images/shpCart/headphone.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":5,
            "name":"iphone",
            "price":1400,
            "image":"images/shpCart/iphone.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":6,
            "name":"ladder",
            "price":30,
            "image":"images/shpCart/ladder.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":7,
            "name":"shirt",
            "price":80,
            "image":"images/shpCart/shirt.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":8,
            "name":"shoe",
            "price":400,
            "image":"images/shpCart/shoe.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":9,
            "name":"tire",
            "price":40,
            "image":"images/shpCart/tire.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":10,
            "name":"Television",
            "price":200,
            "image":"images/shpCart/tv.jpg",
            "quantity":0,
            "added":false
        },
        {
            "id":11,
            "name":"watch",
            "price":800,
            "image":"images/shpCart/watch.jpg", 
            "quantity":0,
            "added":false
        },
        {
            "id":12,
            "name":"table",
            "price":20,
            "image":"images/shpCart/table.jpg",
            "quantity":0,
            "added":false
        }
    ]

    export default products